FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Make the container listen on port 3000 at runtime
EXPOSE 8080

# Define the command to run the app
CMD ["npm", "start"]